[package]
name = "mug-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
anyhow = "1.0.101"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
simplelog = "0.12.2"
log = "0.4.29"
rodio = "0.18.1" # 处理音频播放
indoc = "2.0.7"